language: python

python:
- "3.7"

install:
- pip install -r requirements.txt
- pip install -e .
- pip install coverage
script:
- coverage run -m pytest
after_success:
- bash <(curl -s https://codecov.io/bash)
